### ISSUE TITLE
usecase extensions should be transitive

### ISSUE THREAD

**Issue by uladkasach** [uladkasach/declapract#17]
right now
```yml
# define the different types of combinations of the best practices that we support
use-cases:
  typescript-project:
    practices:
      - cicd-integrate
      - conventional-commits
      - directory-structure-src
      - domain
      - errors
      - format
      - git
      - linting
      - node
      - nonpublished-modules
      - package-json-order
      - prettier
      - testing
      - typescript
      - uuid
  npm-package:
    extends:
      - typescript-project
    practices:
      - cicd-deploy-package
  lambda-service:
    extends:
      - typescript-project
    practices:
      - cicd-deploy-service
      - config
      - dates-and-times
      - environments
      - lambda-clients
      - lambda-handlers
      - logging
      - runtime-type-checking
      - serverless
      - terraform
  lambda-service-with-rds:
    extends:
      - lambda-service
    practices:
      - persist-with-rds
```

results in `lambda-service-with-rds` not having any of the practices listed in `typescript-project`, even though it extends `lambda-service` which extends ` typescript-project`

we would expect that `typescript-project` extension is transitively applied from `lambda-service` extension
